from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/durr1602/gyoza as a module
module gyoza:
    snakefile: 
        github("durr1602/gyoza", path="workflow/Snakefile", tag="89c40d6")
    config:
        config


# use all rules from https://github.com/durr1602/gyoza
use rule * from gyoza
